Repository seker212/Discord_bot, pull requests merged in 2021-04, with the labels that each got.

#32 Set current timezone command and name changes
  core.py
  requirements.txt
  stuff.py
Labels: new feature

#34 Fixes ffmpg dependency
  Dockerfile
  requirements.txt
Labels: container

#40 Added dockerignore
  .dockerignore
  Dockerfile
Labels: container, refactor

#42 Add fuctionality allowing for streaming audio from Youtube
  core.py
  requirements.txt
  ytplayer.py
Labels: new feature

#46 Added sound commands and fixed two bugs here
  .dockerignore
  Dockerfile
  README.md
  core.py
  requirements.txt
  sounds.py
  stuff.py
Labels: bug, new feature, refactor

#47 Pull me when you have time to restart
  README.md
  sounds.py
  ytplayer.py
Labels: refactor

#51 add queue to ytplayer
  ytplayer.py
Labels: new feature
